version: "3.7"
services:
  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: docker/Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - .:/var/www
      - ./docker/php:/usr/local/etc/php/conf.d/
    networks:
      - mynetwork
    depends_on:
      - nginx
      - db
        
  #Nginx Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - mynetwork
 
  #Mysql Service
  db:
    image: mysql:8
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge